### ISSUE TITLE
Android API 31: bottomsheet is going below the virtual buttons.

### ISSUE THREAD

**Issue by softlion** [the49ltd/The49.Maui.BottomSheet#33] opened 2023-06-03 09:44 UTC
I can add a bot padding to the content as a workaround, when android displays those virtual buttons (if I find how to detect that).

![image](https://github.com/the49ltd/The49.Maui.BottomSheet/assets/190756/53901278-472e-4617-80bc-f8a3537b9d61)

Android Simulator Pixel 5 / API 31.

mapsui 4.0.0-rc2

**Comment by softlion** [comment] 2023-06-03 09:45
btw ty for the fix to scrolling.

**Comment by madp4ul** [comment] 2023-06-19 12:42
I observed similar behavior, which might be related to this issue.

## How to reproduce:

1. Set the bottom sheet height to a fixed value, e.g. RatioDetent with Ratio=0.95
2. Set the bottom sheet content up to fill its parent. For example in xaml you could set the content to this:
```
<Grid RowDefinitions="*,100">
            <Grid Grid.Row="0" BackgroundColor="Orange" />
            <Button Grid.Row="1" HeightRequest="100" Text="this will be cut off" />
</Grid>
```
The important part in this example is the "*" which makes the grid take all available space provided by its parent (the bottom sheet).

Running this, you should see that the button is only half visible - if at all. It seems that the bottom sheet provides more space to its child that in should. Taking a smaller ratio for the detent, e.g. 0.6 will cut off a larger portion of the content and the button will not be visible at all.

With Ratio 0.95:
![image](https://github.com/the49ltd/The49.Maui.BottomSheet/assets/19797445/f44eb8ba-c7a0-41b2-a5d6-ca896d62b5e7)

## Investigation

In the android specific BottomSheetManager.cs in the CreateLayout method, specify layout parameters when adding the content containerView to the layout:
![image](https://github.com/the49ltd/The49.Maui.BottomSheet/assets/19797445/0642ef25-ec14-4bbd-913d-80b0442a7dae)

This seems to  help a bit with the issue and might be part of the solution. With this change, different bottom sheet sizes do not influence the overflow size anymore, so RatioDetent with Ratio 0.6 or 0.95 now have the same amount of overflow.

On the Google Pixel 7 Pro (or any Google device actually, I tested a few more using an emulator) the overflow height is now exactly 8 device independent pixels, which is much more consistent than the previous overflow. 

I also tested on the Samsung A52 and here the overflow is 32 dip. So this makes the overflow consistent for across different settings on the same device, but on a different device the overflow height can still be different, indicating that this might be caused by the OS or the screen in any way.

I compared it against the navigation bar height and there does not seems to be a direct linear relationship between the amount of the remaining overflow and the height of the navigation bar: On the Google phones the navigation bar has 24 dip, so 3x the overflow height. On the samsung phone the navigation bar has 48 dip, so 1.5x the overflow height.

I am out of ideas at this point and hoping that someone else can continue the investigation and make this work properly.

**Comment by paulvarache** [comment] 2023-06-21 11:44
I added @madp4ul demo to the sample project and updated the android height sizing to take in account the container height and any potential display cutouts.

Please try rc5 and let me know if this fixes the issue

**Comment by madp4ul** [comment] 2023-06-23 11:22
Unfortunately i dont have the Samsung phone available to me right now so i can not check whether the bottom "padding" is consistent between devices, but it seems to be fixed on the google pixel phone. Thank you very much!

This is the same example in my code base now:

![image](https://github.com/the49ltd/The49.Maui.BottomSheet/assets/19797445/d16a3947-58d8-4848-91f3-41ef55a6b530)

**Comment by paulvarache** [comment] 2023-06-29 09:28
Hi,

A new version was released with a better height calculation logic. Please test it out and let me know if this is still an issue

**Closed** 2023-07-10 13:55 UTC
