### ISSUE TITLE
Blank space appears above Toolbar upon dismissing BottomSheet.

### ISSUE THREAD

**Issue by dg2k** [the49ltd/The49.Maui.BottomSheet#30] opened 2023-05-24 10:16 UTC
This is something new since the latest update.

When BottomSheet is dismissed, it leaves behind a blank space with exact height as the minimal height of BottomSheet.

It is as if the height is defined with absolute px value rather than with Auto, which should collapse to zero height.

**Comment by paulvarache** [comment] 2023-05-25 08:36
This seem a duplicate of #28 will close in favour of that other one

**Closed by paulvarache** 2023-05-25 08:36 UTC
