### ISSUE TITLE
Handle not showing with net 8.0.100-rc.2.23502.2

### ISSUE THREAD

**Issue by shinnthant-lab** [the49ltd/The49.Maui.BottomSheet#62] opened 2023-10-25 04:09 UTC
**HasHandle** property not working with .net 8.0.100-rc.2.23502.2.
-------------------------------------------------------------------------
#Steps to reproduce

1. Create a new .net maui project with .net 8.0.100-rc.2.23502.2.
2. Add a page and add BottomSheet to **OnAppearing** with **HasHandle** property true.
3. Run the app and, handle not showing up.
4. Please see the image for more details

![image](https://github.com/the49ltd/The49.Maui.BottomSheet/assets/54578974/4b83b85b-84f5-43ea-838b-9d04c42fbf57)

#Update
still can't make to work with .net 7 also.
I clone the sample repo and working fine.
but even I cloned the @jfversluis repo in his youtube channel and run, still the handle is missing.

I'm using Visual studio 22 v17.7.5.

[MauiApp1 - BottomSheet Test.zip](https://github.com/the49ltd/The49.Maui.BottomSheet/files/13161627/MauiApp1.-.BottomSheet.Test.zip)

Please see the attached zipped project for more details.

**Comment by paulvarache** [comment] 2023-10-25 08:14
Please make sure you follow the README instruction, more specifically the section about the Android theme.

Duplicate of #54

**Closed by paulvarache** 2023-10-25 08:14 UTC
